# Welcome to Serverless!
service: lambda-lambda

frameworkVersion: '2'

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  lambda-lambda:
    handler: bin/inceptor
    role: LambdaLambdaRole
    timeout: 25
    events:
      - httpApi:
          path: /inceptor
          method: "*"
          
resources:
  Resources:
    LambdaLambdaRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: LambdaLambdaRuntimeRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
                  - apigateway.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: LambdaSelfAdmin
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - 'Fn::Join':
                      - ':'
                      -
                        - 'arn:aws:logs'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - 'log-group:/aws/lambda/*:*:*'
                - Effect: "Allow"
                  Action:
                    - "lambda:*"
                  Resource: "*"
                - Effect: "Allow"
                  Action:
                    - "iam:PassRole"
                  Resource: "*"